### ISSUE TITLE
Checklist for the v4 release

### ISSUE THREAD

**Issue by DavidArno** [DavidArno/SuccincT#58]
List still WIP. Just noting things down as I think of them:

- [x] Remove `Maybe<T>`. See #57
- [x] Convert `Option<T>` and the `Union<>` types to readonly structs. See #57
- [x] Change the way `Succinc<T>` interacts with `null`. See #51.
- [x] Remove Ignore. See #59
- [x] Make `ValueOrError` and `Success` types, readonly (currently just structs).
- [x] Switch the supported framework to netstandard 2
- [x] Add @Odonno's With features (See #44).
- [x] Address issue/PR #48 (@Odonno)
- [x] Address issue/PR #49 (@gavinSteyn) Care needs taking to ensure it doesn't cause problems with C# 8's pattern matching later (I don't think it will, but want to check).
- [x] Address issue/PR #50 (@xlecoustillier)
- [x] Address issue/PR #51 (@xlecoustillier). 
- [x] Make use of the new Enum generic constraint to tidy up the code around the enum parser (#64)
- [x] Check docs for the types that have been changed to structs to see if they need updating to mention this
- [x] Ensure the way that `null` equality is now handled by option and unions is documented
- [x] Document removal of `Ignore` (use discards instead)
- [x] Check whether the enum parser docs mention anything about throwing exceptions if passed a non-enum and remove if they do
- [x] document the new features (this point needs expanding to cover each of them

**Comment by DavidArno** [comment]
Closing this now v4 is released. Missing documentation features are now captured in individual issues.
